project:
  type: website
  output-dir: docs
  

website:
  title: "PsySoc Data Hub"
  favicon: favicon_io/favicon-32x32.png
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Documentation"
        href: documentation/index.qmd
      - text: "Data Access"
        href: data/download.qmd
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "Citation"
        href: citation.qmd
    right:  
      - text: "Dashboards"
        href: dashboards/index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: outreach.qmd
      - icon: github
        href: "https://github.com/"
        aria-label: GitHub

  page-footer:
    center: "Â© 2025 - Centre for Developmental and Motivation Psychology (COM)"
        

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: false
    theme: flatly
    smooth-scroll: true
    highlight-style: github
    code-fold: false
    code-line-numbers: false
    link-external-newwindow: true
    css: styles.css
    grid:
      gutter-width: 2rem


metadata-files:
  - _metadata.yml
